### ISSUE TITLE
No color is extracted when ImageKit plugin is installed

### ISSUE THREAD

**Issue by olach** [iandoe/kirby-dominant-color#1]
As the title says, if the [ImageKit plugin](https://github.com/fabianmichael/kirby-imagekit) is installed, your plugin doesn't work.

I don't know if it's best if you adjust your plugin, or if ImageKit needs to adjust their plugin. But I created this issue to let you know about this issue.

See: https://github.com/fabianmichael/kirby-imagekit/issues/11

**Comment by iandoe** [comment]
Thanks for reporting this. 

This issue is not related to  my plugin since imagekit is producing this issue in other plugins as well, in the issue you linked on their repo, somebody mentions this solution :

`Thanks! Just a correction for others, 'imagekit.lazy' => false is the correct option to use.`

i could add this in my plugin but then i would have to do this for any plugin that infringes on kirby's conventions, not a good practice in my opinion.

**Comment by fabianmichael** [comment]
Hey @iandoe, I can totally understand that this issue is a bit annoying and the goal of ImageKit is to work in the background and just do its job without any hassle. Unfortunately, I don’t know a way to work around this, as I cannot distinguish a thumbs API call from a plugin from one that comes from a template.

I hope there will be a way of solving this in a more elegant fashion in the future, but for now I’m afraid the `imagekit.lazy` option is the simplest way to disable the async behavior of ImageKit. If you don’t want to refer to ImageKit in your plugin, the alternative method could be to use Kirby’s `Thumb` class to generate the temporary thumbnail. By doing this, ImageKit should be skipped as it is only involved, when Thumbnails are created through the `->thumb()` etc. methods or the [thumb component](https://getkirby.com/docs/developer-guide/plugins/components). Note, that optimizers are still applied as they are handled by a wrapper function around the built-in thumb driver (usually `im` or `gd`) directly.

**Comment by iandoe** [comment]
@fabianmichael, thanks for taking the time to weigh in on the issue, i think in that case i'll just add `'imagekit.lazy' => false` to this plugin, that seems to be the best solution for now.

**Comment by fabianmichael** [comment]
One more thing that came across my mind: It might also be worth adding `'imagekit.optimize' => false` to avoid costly optimization of the temporary image.

**Comment by iandoe** [comment]
@fabianmichael 👍
